library(dplyr)

dados <- dados %>%
  mutate(across(starts_with("TPROM_EF"), as.numeric),
         across(starts_with("TPROM_EFAI"), as.numeric),
         across(starts_with("TPROM_EFAF"), as.numeric),
         across(starts_with("TPROM_EF1"), as.numeric),
         across(starts_with("TPROM_EF2"), as.numeric),
         across(starts_with("TPROM_EF3"), as.numeric),
         across(starts_with("TPROM_EF4"), as.numeric),
         across(starts_with("TPROM_EF5"), as.numeric),
         across(starts_with("TPROM_EF6"), as.numeric),
         across(starts_with("TPROM_EF7"), as.numeric),
         across(starts_with("TPROM_EF8"), as.numeric),
         across(starts_with("TPROM_EF9"), as.numeric),
         across(starts_with("TPROM_EM"), as.numeric),
         across(starts_with("TPROM_EM1"), as.numeric),
         across(starts_with("TPROM_EM2"), as.numeric),
         across(starts_with("TPROM_EM3"), as.numeric),
         
         across(starts_with("TREP_EF"), as.numeric),
         across(starts_with("TREP_EFAI"), as.numeric),
         across(starts_with("TREP_EFAF"), as.numeric),
         across(starts_with("TREP_EF1"), as.numeric),
         across(starts_with("TREP_EF2"), as.numeric),
         across(starts_with("TREP_EF3"), as.numeric),
         across(starts_with("TREP_EF4"), as.numeric),
         across(starts_with("TREP_EF5"), as.numeric),
         across(starts_with("TREP_EF6"), as.numeric),
         across(starts_with("TREP_EF7"), as.numeric),
         across(starts_with("TREP_EF8"), as.numeric),
         across(starts_with("TREP_EF9"), as.numeric),
         across(starts_with("TREP_EM"), as.numeric),
         across(starts_with("TREP_EM1"), as.numeric),
         across(starts_with("TREP_EM2"), as.numeric),
         across(starts_with("TREP_EM3"), as.numeric),
         
         across(starts_with("TEV_EF"), as.numeric),
         across(starts_with("TEV_EFAI"), as.numeric),
         across(starts_with("TEV_EFAF"), as.numeric),
         across(starts_with("TEV_EF1"), as.numeric),
         across(starts_with("TEV_EF2"), as.numeric),
         across(starts_with("TEV_EF3"), as.numeric),
         across(starts_with("TEV_EF4"), as.numeric),
         across(starts_with("TEV_EF5"), as.numeric),
         across(starts_with("TEV_EF6"), as.numeric),
         across(starts_with("TEV_EF7"), as.numeric),
         across(starts_with("TEV_EF8"), as.numeric),
         across(starts_with("TEV_EF9"), as.numeric),
         across(starts_with("TEV_EM"), as.numeric),
         across(starts_with("TEV_EM1"), as.numeric),
         across(starts_with("TEV_EM2"), as.numeric),
         across(starts_with("TEV_EM3"), as.numeric))
